name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: NubeEra-Practice/GithubActions@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET != ''}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
# job2:
  #   name: 02.Pushing GithubFiles to S3
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checking Environment Variables
  #       env:
  #         AWS_ACCESS_KEY_ID:	${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY:	${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       run: |
  #         echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
  #         ls /home/runner/work/ -lR
      # - name: AWS CLI Command Configure Checking
      #   run: |
      #     # aws configure
      #     cat ~/.aws/config
      # - name: Running AWS CLI Command
      #   run: |
      #     aws s3 ls
      # - name: Copy Local to S3 using Command
      #   run: |
      #     aws s3 cp ./test.txt s3://bkt28novmujahed/input/local_file.txt