name: Working Github to S3

on: push

jobs:
  job1:
    name: 01.Configuring Environment and System
    runs-on: ubuntu-latest
    steps:
      - name: Configure Environment Variables
        env:
          AWS_ACCESS_KEY_ID:	${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:	${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY          
      - name: 01.Create Folder
        run: |
          mkdir ~/.aws
      - name: 02.Create config file
        run: |
          touch ~/.aws/config
      - name: 03.Update config file
        run: |
          printf '%s\n %s\n %s\n' '[default]' 'region = us-east-1' 'output = table' > ~/.aws/config
      - name: 04.Create credentials file
        run: |
          touch ~/.aws/credentials
      - name: 05.Update credentials file
        run: |
          printf '%s\n %s\n %s\n' '[default]' 'aws_access_key_id = AKIA4RO4QNJEFDQTZI4O' 'aws_secret_access_key = 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' > ~/.aws/credentials      
      - name: 06.Verify config file 
        run: |
          cat ~/.aws/config
      - name: 07.Verify credentials file 
        run: |
          cat ~/.aws/credentials
      - name: 08.Run AWS S3 LS Command
        run: |
          aws s3 ls
      - name: 09.Listing all Recursively
        run: |
          ls /home/runner/work/ -lR
      # - name: Copy Local to S3 using Command
      #   run: |
      #     aws s3 cp ./test.txt s3://bkt28novmujahed/input/local_file.txt
  # job2:
  #   name: 02.Pushing GithubFiles to S3
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checking Environment Variables
  #       env:
  #         AWS_ACCESS_KEY_ID:	${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY:	${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       run: |
  #         echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
  #         ls /home/runner/work/ -lR
      # - name: AWS CLI Command Configure Checking
      #   run: |
      #     # aws configure
      #     cat ~/.aws/config
      # - name: Running AWS CLI Command
      #   run: |
      #     aws s3 ls
      # - name: Copy Local to S3 using Command
      #   run: |
      #     aws s3 cp ./test.txt s3://bkt28novmujahed/input/local_file.txt