name: Working Github to S3

on: push

jobs:
  job1:
    name: 01.Configuring Environment and System
    runs-on: ubuntu-latest
    steps:
      - name: Configure Environment Variables
        env:
          AWS_ACCESS_KEY_ID:	AKIA4RO4QNJEFDQTZI4O
          AWS_SECRET_ACCESS_KEY:	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
        run: |
          echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY          
      - name: 01.Create Folder
        run: |
          mkdir ~/.aws
      - name: 02.Create config file
        run: |
          touch ~/.aws/config
      - name: 03.Update config file
        run: |
          printf '%s\n    %s\n    %s\n' '[default]' 'region = us-east-1' 'output = table' >> ~/.aws/config
      - name: 04.Verify config file 
        run: |
          cat ~/.aws/config
      - name: 05.Run AWS S3 LS Command
        run: |
          aws s3 ls
      # - name: Copy Local to S3 using Command
      #   run: |
      #     aws s3 cp ./test.txt s3://bkt28novmujahed/input/local_file.txt
  job2:
    name: 02.Pushing GithubFiles to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checking Environment Variables
        env:
          AWS_ACCESS_KEY_ID:	AKIA4RO4QNJEFDQTZI4O
          AWS_SECRET_ACCESS_KEY:	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
        run: |
          echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
          ls /home/runner/work/GithubActions/GithubActions/
      # - name: AWS CLI Command Configure Checking
      #   run: |
      #     # aws configure
      #     cat ~/.aws/config
      # - name: Running AWS CLI Command
      #   run: |
      #     aws s3 ls
      # - name: Copy Local to S3 using Command
      #   run: |
      #     aws s3 cp ./test.txt s3://bkt28novmujahed/input/local_file.txt