name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 54.245.73.195
        username: ubuntu
        port: 22
        key_path: '/home/runner/work/GithubActions/GithubActions/kpforall.pem'
        source: "/home/runner/work/GithubActions/GithubActions/action.yml,/home/runner/work/GithubActions/GithubActions/diff-os.yml"
        target: "/home/ubuntu/"
